// Copyright (C) 2025 Leandro Lisboa Penz <lpenz@lpenz.org>
// This file is subject to the terms and conditions defined in
// file 'LICENSE', which is part of this source code package.

use color_eyre::Result;
use pin_project_lite::pin_project;
use std::collections::VecDeque;
use std::pin::Pin;
use std::process::ExitStatus;
use std::task::{Context, Poll};
use tokio_stream::Stream;
use tokio_stream::wrappers::IntervalStream;

use crate::sys_input;
use crate::sys_input::Cmd;
use crate::sys_input::ProcessStream;
use crate::sys_input::SysInputApi;
use crate::time_wrapper::Duration;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputItem {
    LineOut(String),
    LineErr(String),
    Done(ExitStatus),
    Err(std::io::ErrorKind),
    Tick,
}

impl From<sys_input::Item> for InputItem {
    fn from(item: sys_input::Item) -> Self {
        match item {
            sys_input::Item::Stdout(l) => InputItem::LineOut(l),
            sys_input::Item::Stderr(l) => InputItem::LineErr(l),
            sys_input::Item::Done(Ok(sts)) => InputItem::Done(sts),
            sys_input::Item::Done(Err(e)) => InputItem::Err(e),
        }
    }
}

impl From<tokio::time::Instant> for InputItem {
    fn from(_: tokio::time::Instant) -> Self {
        InputItem::Tick
    }
}

impl From<std::io::Error> for InputItem {
    fn from(e: std::io::Error) -> Self {
        InputItem::Err(e.kind())
    }
}

pin_project! {
#[derive(Default)]
pub struct InputStream<SI: SysInputApi> {
    sys_input: SI,
    cmd: Cmd,
    // Events coming from the running process
    process: Option<ProcessStream>,
    // Tick events generated by the [`IntervalStream`] timer
    ticker: Option<IntervalStream>,
    // Used for tests
    testlist: VecDeque<InputItem>,
}
}

impl<SI: SysInputApi> InputStream<SI> {
    pub fn new(sys_input: SI, cmd: Cmd, refresh_delay: Duration) -> Result<Self> {
        Ok(Self {
            sys_input,
            cmd,
            process: None,
            ticker: Some(IntervalStream::new(tokio::time::interval(
                refresh_delay.into(),
            ))),
            testlist: Default::default(),
        })
    }
}

impl<SI: SysInputApi> Stream for InputStream<SI> {
    type Item = InputItem;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.project();
        if let Some(item) = this.testlist.pop_front() {
            return Poll::Ready(Some(item));
        }
        if this.process.is_none() {
            // Run the process if it's not running
            match this.sys_input.run_command(this.cmd.clone()) {
                Ok(process) => *this.process = Some(process),
                Err(e) => return Poll::Ready(Some(InputItem::Err(e.kind()))),
            }
        }
        if let Some(process) = this.process {
            match Pin::new(process).poll_next(cx) {
                Poll::Ready(Some(item)) => {
                    return Poll::Ready(Some(item.into()));
                }
                Poll::Ready(None) => {
                    *this.process = None;
                    *this.ticker = None;
                }
                Poll::Pending => {}
            }
        }
        if let Some(ticker) = this.ticker {
            match Pin::new(ticker).poll_next(cx) {
                Poll::Ready(Some(item)) => Poll::Ready(Some(item.into())),
                _ => Poll::Pending,
            }
        } else {
            Poll::Ready(None)
        }
    }
}

#[cfg(test)]
mod tests {}
