// Copyright (C) 2025 Leandro Lisboa Penz <lpenz@lpenz.org>
// This file is subject to the terms and conditions defined in
// file 'LICENSE', which is part of this source code package.

use color_eyre::Result;
use pin_project::pin_project;
use std::pin::Pin;
use std::process::ExitStatus;
use std::task::{Context, Poll};
use tokio_stream::Stream;
use tokio_stream::wrappers::IntervalStream;

use crate::sys_input;
use crate::sys_input::Cmd;
use crate::sys_input::ProcessStream;
use crate::sys_input::SysInputApi;
use crate::time_wrapper::Duration;
use crate::time_wrapper::Instant;

#[cfg(test)]
use crate::sys_input::SysInputVirtual;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputData {
    Start,
    LineOut(String),
    LineErr(String),
    Done(ExitStatus),
    Err(std::io::ErrorKind),
    Tick,
}

impl From<sys_input::Item> for InputData {
    fn from(item: sys_input::Item) -> Self {
        match item {
            sys_input::Item::Stdout(l) => InputData::LineOut(l),
            sys_input::Item::Stderr(l) => InputData::LineErr(l),
            sys_input::Item::Done(Ok(sts)) => InputData::Done(sts),
            sys_input::Item::Done(Err(e)) => InputData::Err(e),
        }
    }
}

impl From<tokio::time::Instant> for InputData {
    fn from(_: tokio::time::Instant) -> Self {
        InputData::Tick
    }
}

impl From<std::io::Error> for InputData {
    fn from(e: std::io::Error) -> Self {
        InputData::Err(e.kind())
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InputItem {
    pub time: Instant,
    pub data: InputData,
}

impl InputItem {
    pub fn new<D>(time: Instant, data: D) -> InputItem
    where
        D: Into<InputData>,
    {
        Self {
            time,
            data: data.into(),
        }
    }
}

#[pin_project]
#[derive(Default)]
pub struct InputStream<SI: SysInputApi> {
    sys_input: SI,
    cmd: Cmd,
    // Events coming from the running process
    process: Option<ProcessStream>,
    // Tick events generated by the [`IntervalStream`] timer
    ticker: Option<IntervalStream>,
    done: bool,
}

impl<SI: SysInputApi> InputStream<SI> {
    pub fn new(sys_input: SI, cmd: Cmd, refresh_delay: Duration) -> Result<Self> {
        Ok(Self {
            sys_input,
            cmd,
            process: None,
            ticker: Some(IntervalStream::new(tokio::time::interval(
                refresh_delay.into(),
            ))),
            done: false,
        })
    }
}

#[cfg(test)]
impl InputStream<SysInputVirtual> {
    pub fn new_virtual(sys_input: SysInputVirtual) -> Result<Self> {
        Ok(Self {
            sys_input,
            cmd: Cmd::default(),
            process: None,
            ticker: None,
            done: false,
        })
    }
}

impl<SI: SysInputApi> Stream for InputStream<SI> {
    type Item = InputItem;

    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
        let this = self.project();
        let now = this.sys_input.now();
        if *this.done {
            // Trigger a new execution if we are called again.
            *this.process = None;
            *this.done = false;
            return Poll::Ready(None);
        }
        if this.process.is_none() {
            // Run the process if it's not running
            match this.sys_input.run_command(this.cmd.clone()) {
                Ok(process) => *this.process = Some(process),
                Err(e) => return Poll::Ready(Some(InputItem::new(now, e))),
            }
            return Poll::Ready(Some(InputItem::new(now, InputData::Start)));
        }
        if let Some(process) = this.process {
            match Pin::new(process).poll_next(cx) {
                Poll::Ready(Some(item)) => {
                    if matches!(item, sys_input::Item::Done(_)) {
                        // Trigger end of stream:
                        *this.done = true;
                    }
                    return Poll::Ready(Some(InputItem::new(now, item)));
                }
                Poll::Ready(None) => {
                    *this.process = None;
                    *this.ticker = None;
                }
                Poll::Pending => {}
            }
        }
        if let Some(ticker) = this.ticker {
            match Pin::new(ticker).poll_next(cx) {
                Poll::Ready(Some(item)) => Poll::Ready(Some(InputItem::new(now, item))),
                _ => Poll::Pending,
            }
        } else {
            Poll::Ready(None)
        }
    }
}

#[cfg(test)]
mod tests {
    use color_eyre::Result;
    use std::io;
    use tokio_stream::StreamExt;

    use crate::sys_input::Item;
    use crate::sys_input::SysInputVirtual;
    use crate::time_wrapper::Instant;

    use super::*;

    #[tokio::test]
    async fn test_basic_success() -> Result<()> {
        let list = vec![
            Item::Stdout("stdout".into()),
            Item::Stderr("stderr".into()),
            Item::Done(Ok(ExitStatus::default())),
        ];
        let mut sys = SysInputVirtual::default();
        sys.set_items(list.clone());
        let streamer = InputStream::new_virtual(sys)?;
        let streamed = streamer.collect::<Vec<_>>().await;
        let mut now = Instant::default();
        assert_eq!(
            streamed,
            vec![
                InputItem {
                    time: now.incr(),
                    data: InputData::Start
                },
                InputItem {
                    time: now.incr(),
                    data: InputData::LineOut("stdout".to_owned())
                },
                InputItem {
                    time: now.incr(),
                    data: InputData::LineErr("stderr".to_owned())
                },
                InputItem {
                    time: now.incr(),
                    data: InputData::Done(ExitStatus::default())
                }
            ]
        );
        Ok(())
    }

    #[tokio::test]
    async fn test_done_err() -> Result<()> {
        let list = vec![Item::Done(Err(io::ErrorKind::UnexpectedEof))];
        let mut sys = SysInputVirtual::default();
        sys.set_items(list.clone());
        let streamer = InputStream::new_virtual(sys)?;
        let streamed = streamer.collect::<Vec<_>>().await;
        let mut now = Instant::default();
        assert_eq!(
            streamed,
            vec![
                InputItem {
                    time: now.incr(),
                    data: InputData::Start,
                },
                InputItem {
                    time: now.incr(),
                    data: InputData::Err(io::ErrorKind::UnexpectedEof)
                }
            ]
        );
        Ok(())
    }
}
