---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    uses: lpenz/omnilint/.github/workflows/omnilint.yml@v0.5.2
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.23.3
    with:
      coveralls: true
      deb: true
      publish_cratesio: true
      publish_github_release: true
      publish_github_release_files: |
        target/release/ogle target/release/ogle.1
      publish_packagecloud: true
      publish_packagecloud_repository: |
        ["debian/debian/bullseye",
         "debian/debian/bookworm",
         "ubuntu/ubuntu/jammy"]
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build
      - run: nix flake check
  publish-cachix:
    needs: [ omnilint, rust, nix ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.14.0
      - uses: cachix/install-nix-action@v29
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v15
        with:
          skipPush: ${{ steps.version.outputs.version_commit == '' }}
          name: lpenz
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build
      - run: nix flake check
