---
name: CI
on:  # yamllint disable-line rule:truthy
  - workflow_dispatch
  - push
  - pull_request
jobs:
  omnilint:
    uses: lpenz/omnilint/.github/workflows/omnilint.yml@v0.5.2
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.26.3
    with:
      coveralls: true
      deb: true
      rpm: true
      enable_cargo-semver-checks: false
      publish_cratesio: true
      publish_github_release: true
      publish_github_release_files: |
        target/release/ogle
        target/release/ogle.1
      publish_packagecloud_repository_deb: |
        ["debian/debian/trixie",
         "ubuntu/ubuntu/noble"]
      publish_packagecloud_repository_rpm: |
        ["rpm/rpm_any/rpm_any"]
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
